version: '3'
services:
    youmee_admin:
        image: louisbenedictb/youmee:latest

    redis-cache:
        build:
            - ./redis

    proxy:
        build:
            - ./proxy
        restart: always
        depends_on:
            - youmee_admin
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./proxy/ssl:/etc/nginx/ssl
            - type: bind
              source: ./proxy/default.conf
              target: /etc/nginx/conf.d
        command: |
            /bin/sh -c "nginx -g 'daemon off;'"
