services:
    web-app:
        image: louisbenedictb/youmee:latest

    redis-cache:
        image: redis:7.0-alpine

    reverse-proxy:
        image: nginx:alpine-1
        restart: always
        depends_on:
            - web-app
        environment:
            - HOST=${HOST}
            - HOST=${HOST}
            - HOST=${HOST}
        container_name: nginx-youmee
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./proxy/src:/usr/share/nginx/html
            - ./proxy/ssl:/etc/nginx/ssl
            - type: bind
              source: ./proxy/nginx.conf.template
              target: /etc/nginx/nginx.conf.template
        command: |
            /
            /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
