version: '3'
services:
    youmee_admin:
        image: louisbenedictb/youmee:latest

    redis-cache:
        image: redis:7.0-alpine

    reverse_proxy:
        image: nginx:1-alpine
        restart: always
        depends_on:
            - youmee_admin
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./proxy/src:/usr/share/nginx/html
            - ./proxy/ssl:/etc/nginx/ssl
            - type: bind
              source: ./proxy/nginx.conf
              target: /etc/nginx/nginx.conf
        command: |
            /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
