name: Build and Deploy
on:
    push:
        branches: [main]

jobs:
    build-push-image:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_ACCESSTOKEN}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            # Public secrets need to be injected at build-time
            #  https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables
            - name: Setup production environment
              env:
                  HOST: ${{secrets.DOMAINNAME}}
                  APIPORT: 3000
                  APIVERSION: 'v1'
                  PROTOCOL: https
                  PORT: 3000
                  NEXT_PUBLIC_S3_URL: ${{ secrets.NEXT_PUBLIC_S3_URL}}
                  NEXT_PUBLIC_CF_URL: ${{ secrets.NEXT_PUBLIC_CF_URL}}
                  EMAIL_SENDER: ${{secrets.EMAIL_FROM}}
              run: |
                  ls -lA
                  cd ..
                  cat <<EOF > .env
                  NODE_ENV=production
                  NEXTAUTH_URL="$PROTOCOL://$HOST:$PORT/api/$APIVERSION/auth"
                  NEXT_PUBLIC_S3_URL="$NEXT_PUBLIC_S3_URL"
                  NEXT_PUBLIC_CF_URL="$NEXT_PUBLIC_CF_URL"
                  NEXT_PUBLIC_EMAIL_SENDER="$EMAIL_SENDER"
                  NEXT_PUBLIC_BASEURL="$PROTOCOL://$HOST:$PORT"
                  NEXT_PUBLIC_API_BASEURL="/api/$APIVERSION"
                  EOF
                  ls -lA

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  file: Dockerfile
                  push: true
                  tags: |
                      louisbenedictb/youmee:latest
                      louisbenedictb/youmee:${{github.sha}}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new

            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
