name: Build and Deploy

on:
    push:
        branches: [main]

jobs:
    docker-build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v3
            # This is the a separate action that sets up buildx runner
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_ACCESSTOKEN}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            # So now you can use Actions' own caching!

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  file: Dockerfile
                  push: true
                  tags: louisbenedictb/youmee:latest
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new

            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
