name: CI Pipeline

on: [push]

branches: [dev]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

          - name: Install Dependencies
          - run: npm install

          - name: Run Lint
          - run: npm run lint

          - name: Jest Testsuite
          - run: npm test
