name: CI Pipeline

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    test:
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Install Dependencies
              run: npm install

            - name: Run Lint
              run: npm run lint

            - name: Jest Unittests
              env:
                  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
              run: npm test:coverage

    docker-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # This is the a separate action that sets up buildx runner
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            # So now you can use Actions' own caching!
            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-
            # And make it available for the builds
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile
                  push: false
                  tags: user/app:latest
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
