name: CI Pipeline

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    tests:
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Jest Unittests
              env:
                  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
              run: npm run test:coverage
    automerge-master:
        name: Auto Merge main
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.CICD_GITHUB_ACCESS_TOKEN }}

            - name: create pull request
              id: open-pr
              uses: repo-sync/pull-request@v2
              with:
                  github_token: ${{ secrets.CICD_GITHUB_ACCESS_TOKEN }}
                  destination_branch: ${{ github.event.repository.default_branch }}
                  pr_title: '[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}'
                  pr_body: 'Automated Pull Request'

            - name: enable automerge
              if: steps.open-pr.outputs.pr_number != ''
              uses: peter-evans/enable-pull-request-automerge@v2
              with:
                  token: ${{ secrets.CICD_GITHUB_ACCESS_TOKEN }}
                  pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
                  merge-method: merge
